# -*- coding: utf-8 -*-
"""
Quality report for comparing original and synthetic DataFrames.

Generates a self-contained HTML file with distribution comparisons,
correlation analysis, PSI scores, and an ML utility benchmark.
"""

import base64
import io
import logging
from typing import Dict, List, Optional

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score, accuracy_score
from sklearn.model_selection import cross_val_predict

from tabgan.utils import calculate_psi

__all__ = ["QualityReport"]

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>TabGAN Quality Report</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         max-width: 1100px; margin: 0 auto; padding: 24px; color: #222; }}
  h1 {{ border-bottom: 2px solid #4a90d9; padding-bottom: 8px; }}
  h2 {{ color: #4a90d9; margin-top: 36px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
  th {{ background: #4a90d9; color: #fff; }}
  tr:nth-child(even) {{ background: #f5f7fa; }}
  .score {{ font-size: 2em; font-weight: bold; color: #4a90d9; }}
  .metric-card {{ display: inline-block; border: 1px solid #ddd; border-radius: 8px;
                  padding: 16px 24px; margin: 8px; text-align: center; }}
  img.chart {{ max-width: 100%; height: auto; }}
  .grid {{ display: flex; flex-wrap: wrap; gap: 12px; }}
  .grid img {{ flex: 1 1 45%; min-width: 300px; }}
</style>
</head>
<body>
<h1>TabGAN Quality Report</h1>
<p>Original: {n_orig} rows &times; {n_cols} cols &nbsp;|&nbsp;
   Synthetic: {n_synth} rows &times; {n_cols} cols</p>

<div>
  <div class="metric-card">
    <div>Overall Score</div>
    <div class="score">{overall_score:.2f}</div>
  </div>
  <div class="metric-card">
    <div>ML Utility</div>
    <div class="score">{ml_utility:.2f}</div>
  </div>
  <div class="metric-card">
    <div>Mean PSI</div>
    <div class="score">{mean_psi:.3f}</div>
  </div>
  {timing_card}
</div>

<h2>Column Statistics</h2>
{column_stats_html}

<h2>PSI per Column</h2>
{psi_html}

<h2>Correlation Comparison</h2>
<div class="grid">
{corr_images}
</div>

<h2>Distribution Comparison</h2>
<div class="grid">
{dist_images}
</div>

<h2>ML Utility Detail</h2>
{ml_detail_html}

<hr>
<p style="color:#999; font-size:0.85em">Generated by TabGAN QualityReport</p>
</body>
</html>
"""


def _fig_to_base64(fig) -> str:
    """Render a matplotlib figure to a base64-encoded PNG data URI."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight", dpi=100)
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode("utf-8")
    buf.close()
    return f"data:image/png;base64,{b64}"


class QualityReport:
    """Compare original and synthetic DataFrames across multiple quality axes.

    Args:
        original_df: Real data.
        synthetic_df: Synthetic data (must have the same columns).
        cat_cols: Names of categorical columns (affects stats display).
        target_col: Optional target column name for ML utility evaluation.

    Example::

        report = QualityReport(orig, synth, cat_cols=["gender"]).compute()
        report.to_html("report.html")
        print(report.summary())
    """

    def __init__(
        self,
        original_df: pd.DataFrame,
        synthetic_df: pd.DataFrame,
        cat_cols: Optional[List[str]] = None,
        target_col: Optional[str] = None,
        generation_timing: Optional[Dict[str, float]] = None,
    ):
        shared = [c for c in original_df.columns if c in synthetic_df.columns]
        self.original = original_df[shared].copy()
        self.synthetic = synthetic_df[shared].copy()
        self.cat_cols = [c for c in (cat_cols or []) if c in shared]
        self.target_col = target_col
        self.generation_timing = generation_timing
        self._results: Dict = {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def compute(self) -> "QualityReport":
        """Run all metrics and store results internally."""
        self._results["column_stats"] = self._column_stats()
        self._results["psi"] = self._psi_per_column()
        self._results["correlation"] = self._correlation_comparison()
        self._results["ml_utility"] = self._ml_utility_score()
        self._results["overall"] = self._overall_score()
        return self

    def summary(self) -> Dict:
        """Return a dict of all metric results (without images)."""
        if not self._results:
            self.compute()
        result = {
            "column_stats": self._results["column_stats"],
            "psi": {k: v for k, v in self._results["psi"].items()},
            "ml_utility": self._results["ml_utility"],
            "overall_score": self._results["overall"],
        }
        if self.generation_timing:
            result["generation_timing"] = self.generation_timing
        return result

    def to_html(self, path: str) -> None:
        """Write a self-contained HTML report to *path*."""
        if not self._results:
            self.compute()

        psi = self._results["psi"]
        ml = self._results["ml_utility"]

        # Column stats table
        stats = self._results["column_stats"]
        col_rows = []
        for col, s in stats.items():
            if s["dtype"] == "numeric":
                col_rows.append(
                    f"<tr><td>{col}</td><td>numeric</td>"
                    f"<td>{s['orig_mean']:.3f}</td><td>{s['synth_mean']:.3f}</td>"
                    f"<td>{s['orig_std']:.3f}</td><td>{s['synth_std']:.3f}</td></tr>"
                )
            else:
                col_rows.append(
                    f"<tr><td>{col}</td><td>categorical</td>"
                    f"<td colspan='2'>unique: {s['orig_nunique']}</td>"
                    f"<td colspan='2'>unique: {s['synth_nunique']}</td></tr>"
                )
        col_stats_html = (
            "<table><tr><th>Column</th><th>Type</th>"
            "<th>Orig Mean/Info</th><th>Synth Mean/Info</th>"
            "<th>Orig Std/Info</th><th>Synth Std/Info</th></tr>"
            + "\n".join(col_rows) + "</table>"
        )

        # PSI table
        psi_rows = "".join(
            f"<tr><td>{col}</td><td>{val:.4f}</td></tr>"
            for col, val in psi.items() if col != "mean"
        )
        psi_html = (
            f"<table><tr><th>Column</th><th>PSI</th></tr>{psi_rows}</table>"
        )

        # Correlation images
        corr_imgs = self._render_correlation_plots()
        corr_html = "\n".join(
            f'<img class="chart" src="{src}" alt="{label}">'
            for label, src in corr_imgs.items()
        )

        # Distribution images
        dist_imgs = self._render_distribution_plots()
        dist_html = "\n".join(
            f'<img class="chart" src="{src}" alt="{col}">'
            for col, src in dist_imgs.items()
        )

        # ML utility detail
        ml_html = (
            f"<p>Train-on-Synthetic, Test-on-Real AUC: <b>{ml.get('tstr_auc', 'N/A')}</b></p>"
            f"<p>Train-on-Real, Test-on-Real AUC (baseline): <b>{ml.get('trtr_auc', 'N/A')}</b></p>"
            f"<p>Utility ratio: <b>{ml.get('utility_ratio', 'N/A')}</b></p>"
        )

        numeric_psi = [v for k, v in psi.items() if k != "mean" and isinstance(v, (int, float))]
        mean_psi = float(np.mean(numeric_psi)) if numeric_psi else 0.0

        # Timing card
        timing_card = ""
        if self.generation_timing and "total" in self.generation_timing:
            total_s = self.generation_timing["total"]
            if total_s < 1:
                t_str = f"{total_s * 1000:.0f}ms"
            elif total_s < 60:
                t_str = f"{total_s:.1f}s"
            else:
                t_str = f"{total_s / 60:.1f}min"
            timing_card = (
                f'<div class="metric-card">'
                f"<div>Generation Time</div>"
                f'<div class="score">{t_str}</div>'
                f"</div>"
            )

        html = _HTML_TEMPLATE.format(
            n_orig=len(self.original),
            n_synth=len(self.synthetic),
            n_cols=len(self.original.columns),
            overall_score=self._results["overall"],
            ml_utility=ml.get("utility_ratio", 0.0),
            mean_psi=mean_psi,
            column_stats_html=col_stats_html,
            psi_html=psi_html,
            corr_images=corr_html,
            dist_images=dist_html,
            ml_detail_html=ml_html,
            timing_card=timing_card,
        )

        with open(path, "w", encoding="utf-8") as fh:
            fh.write(html)
        logging.info(f"Quality report written to {path}")

    # ------------------------------------------------------------------
    # Private metric methods
    # ------------------------------------------------------------------
    def _column_stats(self) -> Dict:
        stats = {}
        for col in self.original.columns:
            if col in self.cat_cols or not pd.api.types.is_numeric_dtype(self.original[col]):
                stats[col] = {
                    "dtype": "categorical",
                    "orig_nunique": int(self.original[col].nunique()),
                    "synth_nunique": int(self.synthetic[col].nunique()),
                }
            else:
                stats[col] = {
                    "dtype": "numeric",
                    "orig_mean": float(self.original[col].mean()),
                    "synth_mean": float(self.synthetic[col].mean()),
                    "orig_std": float(self.original[col].std()),
                    "synth_std": float(self.synthetic[col].std()),
                    "orig_min": float(self.original[col].min()),
                    "synth_min": float(self.synthetic[col].min()),
                    "orig_max": float(self.original[col].max()),
                    "synth_max": float(self.synthetic[col].max()),
                }
        return stats

    def _psi_per_column(self) -> Dict:
        psi_dict = {}
        numeric_cols = self.original.select_dtypes(include=[np.number]).columns
        for col in numeric_cols:
            try:
                val = float(calculate_psi(
                    self.original[col].values,
                    self.synthetic[col].values,
                    buckets=10,
                ))
            except Exception:
                val = float("nan")
            psi_dict[col] = val
        vals = [v for v in psi_dict.values() if np.isfinite(v)]
        psi_dict["mean"] = float(np.mean(vals)) if vals else 0.0
        return psi_dict

    def _correlation_comparison(self) -> Dict:
        numeric_orig = self.original.select_dtypes(include=[np.number])
        numeric_synth = self.synthetic.select_dtypes(include=[np.number])
        if numeric_orig.shape[1] < 2:
            return {"orig_corr": None, "synth_corr": None, "diff_mean": 0.0}
        orig_corr = numeric_orig.corr()
        synth_corr = numeric_synth.corr()
        diff = (orig_corr - synth_corr).abs()
        return {
            "orig_corr": orig_corr,
            "synth_corr": synth_corr,
            "diff_mean": float(diff.mean().mean()),
        }

    def _ml_utility_score(self) -> Dict:
        """Train-on-Synthetic, Test-on-Real (TSTR) evaluation."""
        from sklearn.ensemble import GradientBoostingClassifier

        target = self.target_col
        if target is None or target not in self.original.columns or target not in self.synthetic.columns:
            return {"tstr_auc": None, "trtr_auc": None, "utility_ratio": 0.0}

        orig_num = self.original.select_dtypes(include=[np.number])
        synth_num = self.synthetic.select_dtypes(include=[np.number])

        if target not in orig_num.columns:
            return {"tstr_auc": None, "trtr_auc": None, "utility_ratio": 0.0}

        X_real = orig_num.drop(columns=[target]).values
        y_real = orig_num[target].values
        X_synth = synth_num.drop(columns=[target]).values
        y_synth = synth_num[target].values

        if len(np.unique(y_real)) < 2 or len(np.unique(y_synth)) < 2:
            return {"tstr_auc": None, "trtr_auc": None, "utility_ratio": 0.0}

        try:
            clf_real = GradientBoostingClassifier(n_estimators=50, max_depth=3, random_state=42)
            proba_real = cross_val_predict(clf_real, X_real, y_real, cv=3, method="predict_proba")[:, 1]
            trtr_auc = float(roc_auc_score(y_real, proba_real))

            clf_synth = GradientBoostingClassifier(n_estimators=50, max_depth=3, random_state=42)
            clf_synth.fit(X_synth, y_synth)
            proba_synth = clf_synth.predict_proba(X_real)[:, 1]
            tstr_auc = float(roc_auc_score(y_real, proba_synth))

            ratio = tstr_auc / trtr_auc if trtr_auc > 0 else 0.0
        except Exception as e:
            logging.warning(f"ML utility evaluation failed: {e}")
            return {"tstr_auc": None, "trtr_auc": None, "utility_ratio": 0.0}

        return {
            "tstr_auc": round(tstr_auc, 4),
            "trtr_auc": round(trtr_auc, 4),
            "utility_ratio": round(min(ratio, 1.0), 4),
        }

    def _overall_score(self) -> float:
        psi_vals = [v for k, v in self._results["psi"].items()
                    if k != "mean" and isinstance(v, (int, float)) and np.isfinite(v)]
        # PSI component: lower is better → score = 1/(1+mean_psi)
        mean_psi = float(np.mean(psi_vals)) if psi_vals else 0.0
        psi_score = 1.0 / (1.0 + mean_psi)

        # Correlation component
        corr_diff = self._results["correlation"]["diff_mean"]
        corr_score = max(1.0 - corr_diff, 0.0)

        # ML utility component
        ml_ratio = self._results["ml_utility"].get("utility_ratio", 0.0) or 0.0

        overall = 0.35 * psi_score + 0.30 * corr_score + 0.35 * ml_ratio
        return round(min(max(overall, 0.0), 1.0), 4)

    # ------------------------------------------------------------------
    # Chart renderers (require matplotlib — lazy import)
    # ------------------------------------------------------------------
    def _render_correlation_plots(self) -> Dict[str, str]:
        try:
            import matplotlib
            matplotlib.use("Agg")
            import matplotlib.pyplot as plt
        except ImportError:
            logging.warning("matplotlib not installed — skipping correlation plots")
            return {}

        corr = self._results["correlation"]
        if corr["orig_corr"] is None:
            return {}

        images = {}
        for label, matrix in [("Original", corr["orig_corr"]), ("Synthetic", corr["synth_corr"])]:
            fig, ax = plt.subplots(figsize=(5, 4))
            im = ax.imshow(matrix.values, cmap="RdBu_r", vmin=-1, vmax=1)
            ax.set_xticks(range(len(matrix.columns)))
            ax.set_yticks(range(len(matrix.columns)))
            ax.set_xticklabels(matrix.columns, rotation=45, ha="right", fontsize=7)
            ax.set_yticklabels(matrix.columns, fontsize=7)
            ax.set_title(f"{label} Correlation")
            fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
            images[label] = _fig_to_base64(fig)
            plt.close(fig)

        return images

    def _render_distribution_plots(self) -> Dict[str, str]:
        try:
            import matplotlib
            matplotlib.use("Agg")
            import matplotlib.pyplot as plt
        except ImportError:
            logging.warning("matplotlib not installed — skipping distribution plots")
            return {}

        images = {}
        for col in self.original.columns:
            if not pd.api.types.is_numeric_dtype(self.original[col]):
                continue
            fig, ax = plt.subplots(figsize=(4, 3))
            ax.hist(self.original[col].dropna(), bins=30, alpha=0.5, label="Original", density=True)
            ax.hist(self.synthetic[col].dropna(), bins=30, alpha=0.5, label="Synthetic", density=True)
            ax.set_title(col, fontsize=10)
            ax.legend(fontsize=7)
            images[col] = _fig_to_base64(fig)
            plt.close(fig)

        return images
